### ISSUE TITLE
Rename folder Matio to MatIO

### ISSUE THREAD

**Issue by klugier** [anboto/MATIO#1]
The package name is MatIO when the folder name in directory is Matio. This might be incompatible with POSIX, because it takes into account the size of the letters in directory name,.

Also, consider changing the name of the repository from MATIO to MatIO for consistency.

**Comment by izabala123** [comment]
Thank you. It is now fixed. 

It is curious that in my PC that was already fixed, so GitHub didn't consider changing letters case was a real renaming.

Iñaki
